// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItOPqgPqLM2eCHfRcpk1rebSE9mUUO1c',
    appId: '1:926176690413:web:4b61b8ca6cd8db6c584ce4',
    messagingSenderId: '926176690413',
    projectId: 'fluttertest-ae1fe',
    authDomain: 'fluttertest-ae1fe.firebaseapp.com',
    storageBucket: 'fluttertest-ae1fe.appspot.com',
    measurementId: 'G-P7MJGK7QMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_wk9OJXdhQVFfUF-IiQwamixp6ygsk4',
    appId: '1:926176690413:android:dd6b4a6616dd38e8584ce4',
    messagingSenderId: '926176690413',
    projectId: 'fluttertest-ae1fe',
    storageBucket: 'fluttertest-ae1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9CZRI_cAKr78UCpjCjq8BzOgNR1tF1E',
    appId: '1:926176690413:ios:8b03d92df2ad0d19584ce4',
    messagingSenderId: '926176690413',
    projectId: 'fluttertest-ae1fe',
    storageBucket: 'fluttertest-ae1fe.appspot.com',
    iosClientId: '926176690413-7vosiatpeub1b459h1euk1c835tv801o.apps.googleusercontent.com',
    iosBundleId: 'com.firestore.test.flutterFirestoreTest',
  );
}
